import 'dart:developer';
import 'dart:io';
import 'dart:ui';
// import 'dart:js_util';

import 'package:carousel_slider/carousel_slider.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:freshly/src/app.dart';
import 'package:go_router/go_router.dart';
import 'package:freshly/src/blocs/blocs.dart';
import 'package:freshly/src/cubits/cubits.dart';
import 'package:freshly/src/models/models.dart';
import 'package:freshly/src/utilities/utilities.dart';
import 'package:freshly/src/widgets/widgets.dart';
import 'package:google_nav_bar/google_nav_bar.dart';
import 'package:lottie/lottie.dart';
import 'package:velocity_x/velocity_x.dart';

part 'splash_screen.dart';
part 'register_screen.dart';
part 'login_screen.dart';
part 'login_screen2.dart';
part 'home/home_screen.dart';
part 'home/views/dashboard_view.dart';
part 'home/views/wishlist_view.dart';
part 'home/views/user_view.dart';
part 'home/views/search_view.dart';
part 'admin_screen.dart';
part 'detail_screen.dart';
part 'cart_screen.dart';
part 'my_order_screen.dart';
